### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by xsmart** [ashafiei/tmf#20]
Can the license to be lgpl ,then we can continue update the tmf,also this framework can be used as in commercial projects?

**Comment by ashafiei** [comment]
Would you be interested in updating it also on github as an open-source project?
My interest is in DASH video streaming. I would like to have a filter for DASH streaming.

The final result that I would like to have is an application using tmf which receives a live video from webcam and streams it using DASH protocol.

**Comment by xsmart** [comment]
Yes,we are developing the video surveillance system,but some parts are commercial,we will make the tmf open if we update it,so if you change the license to lgpl ,we will join to develop,
The gstreamer is lgpl.

**Comment by xsmart** [comment]
Ffmpeg is also lgpl.

**Comment by ashafiei** [comment]
Thanks for the feedback. I will change the licence.

**Comment by ashafiei** [comment]
The licence has been updated to LGPL 3.0

**Comment by xsmart** [comment]
great！

**Comment by ashafiei** [comment]
Let me know if I have to add contributors to the project.
